project:
  type: website

website:
  title: "erikadataspace"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/erikastats
      - icon: linkedin
        href: https://www.linkedin.com/in/erika-borelli-08951214a/
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

